// Generated by gencpp from file seagull_commons_msgs/CommsParameters.msg
// DO NOT EDIT!


#ifndef SEAGULL_COMMONS_MSGS_MESSAGE_COMMSPARAMETERS_H
#define SEAGULL_COMMONS_MSGS_MESSAGE_COMMSPARAMETERS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <seagull_commons_msgs/SeagullHeader.h>

namespace seagull_commons_msgs
{
template <class ContainerAllocator>
struct CommsParameters_
{
  typedef CommsParameters_<ContainerAllocator> Type;

  CommsParameters_()
    : header()
    , retries(0)
    , timeout(0)
    , dispatch_rate(0)  {
    }
  CommsParameters_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , retries(0)
    , timeout(0)
    , dispatch_rate(0)  {
    }



   typedef  ::seagull_commons_msgs::SeagullHeader_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int8_t _retries_type;
  _retries_type retries;

   typedef int16_t _timeout_type;
  _timeout_type timeout;

   typedef int16_t _dispatch_rate_type;
  _dispatch_rate_type dispatch_rate;




  typedef boost::shared_ptr< ::seagull_commons_msgs::CommsParameters_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::seagull_commons_msgs::CommsParameters_<ContainerAllocator> const> ConstPtr;

}; // struct CommsParameters_

typedef ::seagull_commons_msgs::CommsParameters_<std::allocator<void> > CommsParameters;

typedef boost::shared_ptr< ::seagull_commons_msgs::CommsParameters > CommsParametersPtr;
typedef boost::shared_ptr< ::seagull_commons_msgs::CommsParameters const> CommsParametersConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::seagull_commons_msgs::CommsParameters_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::seagull_commons_msgs::CommsParameters_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace seagull_commons_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'seagull_commons_msgs': ['/home/eloi/seagull_ws_dev/src/seagull_commons_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::seagull_commons_msgs::CommsParameters_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::seagull_commons_msgs::CommsParameters_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::seagull_commons_msgs::CommsParameters_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::seagull_commons_msgs::CommsParameters_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::seagull_commons_msgs::CommsParameters_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::seagull_commons_msgs::CommsParameters_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::seagull_commons_msgs::CommsParameters_<ContainerAllocator> >
{
  static const char* value()
  {
    return "389b742ee095b87f5422f6fc00ec3306";
  }

  static const char* value(const ::seagull_commons_msgs::CommsParameters_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x389b742ee095b87fULL;
  static const uint64_t static_value2 = 0x5422f6fc00ec3306ULL;
};

template<class ContainerAllocator>
struct DataType< ::seagull_commons_msgs::CommsParameters_<ContainerAllocator> >
{
  static const char* value()
  {
    return "seagull_commons_msgs/CommsParameters";
  }

  static const char* value(const ::seagull_commons_msgs::CommsParameters_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::seagull_commons_msgs::CommsParameters_<ContainerAllocator> >
{
  static const char* value()
  {
    return "SeagullHeader header\n\
int8 retries\n\
int16 timeout\n\
int16 dispatch_rate\n\
\n\
================================================================================\n\
MSG: seagull_commons_msgs/SeagullHeader\n\
Header header\n\
uint16 vehicleId\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::seagull_commons_msgs::CommsParameters_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::seagull_commons_msgs::CommsParameters_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.retries);
      stream.next(m.timeout);
      stream.next(m.dispatch_rate);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct CommsParameters_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::seagull_commons_msgs::CommsParameters_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::seagull_commons_msgs::CommsParameters_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::seagull_commons_msgs::SeagullHeader_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "retries: ";
    Printer<int8_t>::stream(s, indent + "  ", v.retries);
    s << indent << "timeout: ";
    Printer<int16_t>::stream(s, indent + "  ", v.timeout);
    s << indent << "dispatch_rate: ";
    Printer<int16_t>::stream(s, indent + "  ", v.dispatch_rate);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SEAGULL_COMMONS_MSGS_MESSAGE_COMMSPARAMETERS_H
