// Generated by gencpp from file seagull_autopilot_msgs/AutopilotTelemetry.msg
// DO NOT EDIT!


#ifndef SEAGULL_AUTOPILOT_MSGS_MESSAGE_AUTOPILOTTELEMETRY_H
#define SEAGULL_AUTOPILOT_MSGS_MESSAGE_AUTOPILOTTELEMETRY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <seagull_commons_msgs/SeagullHeader.h>

namespace seagull_autopilot_msgs
{
template <class ContainerAllocator>
struct AutopilotTelemetry_
{
  typedef AutopilotTelemetry_<ContainerAllocator> Type;

  AutopilotTelemetry_()
    : header()
    , latitude(0.0)
    , longitude(0.0)
    , altitude(0.0)
    , ias(0)
    , vx(0)
    , vy(0)
    , vz(0)
    , roll(0)
    , pitch(0)
    , yaw(0.0)
    , barometricAltitude(0)
    , windSouth(0.0)
    , windWest(0.0)
    , leftRPM(0)
    , rightRPM(0)
    , staticPressure(0)
    , accelX(0)
    , accelY(0)
    , accelZ(0)
    , compass(0)
    , agl(0)
    , timestamp(0)
    , fuel(0.0)  {
    }
  AutopilotTelemetry_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , latitude(0.0)
    , longitude(0.0)
    , altitude(0.0)
    , ias(0)
    , vx(0)
    , vy(0)
    , vz(0)
    , roll(0)
    , pitch(0)
    , yaw(0.0)
    , barometricAltitude(0)
    , windSouth(0.0)
    , windWest(0.0)
    , leftRPM(0)
    , rightRPM(0)
    , staticPressure(0)
    , accelX(0)
    , accelY(0)
    , accelZ(0)
    , compass(0)
    , agl(0)
    , timestamp(0)
    , fuel(0.0)  {
    }



   typedef  ::seagull_commons_msgs::SeagullHeader_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _latitude_type;
  _latitude_type latitude;

   typedef float _longitude_type;
  _longitude_type longitude;

   typedef float _altitude_type;
  _altitude_type altitude;

   typedef uint16_t _ias_type;
  _ias_type ias;

   typedef int16_t _vx_type;
  _vx_type vx;

   typedef int16_t _vy_type;
  _vy_type vy;

   typedef int16_t _vz_type;
  _vz_type vz;

   typedef int16_t _roll_type;
  _roll_type roll;

   typedef int16_t _pitch_type;
  _pitch_type pitch;

   typedef float _yaw_type;
  _yaw_type yaw;

   typedef int16_t _barometricAltitude_type;
  _barometricAltitude_type barometricAltitude;

   typedef float _windSouth_type;
  _windSouth_type windSouth;

   typedef float _windWest_type;
  _windWest_type windWest;

   typedef uint16_t _leftRPM_type;
  _leftRPM_type leftRPM;

   typedef uint16_t _rightRPM_type;
  _rightRPM_type rightRPM;

   typedef uint16_t _staticPressure_type;
  _staticPressure_type staticPressure;

   typedef int16_t _accelX_type;
  _accelX_type accelX;

   typedef int16_t _accelY_type;
  _accelY_type accelY;

   typedef int16_t _accelZ_type;
  _accelZ_type accelZ;

   typedef uint16_t _compass_type;
  _compass_type compass;

   typedef uint16_t _agl_type;
  _agl_type agl;

   typedef uint64_t _timestamp_type;
  _timestamp_type timestamp;

   typedef float _fuel_type;
  _fuel_type fuel;




  typedef boost::shared_ptr< ::seagull_autopilot_msgs::AutopilotTelemetry_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::seagull_autopilot_msgs::AutopilotTelemetry_<ContainerAllocator> const> ConstPtr;

}; // struct AutopilotTelemetry_

typedef ::seagull_autopilot_msgs::AutopilotTelemetry_<std::allocator<void> > AutopilotTelemetry;

typedef boost::shared_ptr< ::seagull_autopilot_msgs::AutopilotTelemetry > AutopilotTelemetryPtr;
typedef boost::shared_ptr< ::seagull_autopilot_msgs::AutopilotTelemetry const> AutopilotTelemetryConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::seagull_autopilot_msgs::AutopilotTelemetry_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::seagull_autopilot_msgs::AutopilotTelemetry_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace seagull_autopilot_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'seagull_autopilot_msgs': ['/home/ciafa/sharpeye15/sharpeye15_ws/src/seagull_autopilot_msgs/msg'], 'seagull_commons_msgs': ['/home/ciafa/sharpeye15/sharpeye15_ws/src/seagull_commons_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::seagull_autopilot_msgs::AutopilotTelemetry_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::seagull_autopilot_msgs::AutopilotTelemetry_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::seagull_autopilot_msgs::AutopilotTelemetry_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::seagull_autopilot_msgs::AutopilotTelemetry_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::seagull_autopilot_msgs::AutopilotTelemetry_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::seagull_autopilot_msgs::AutopilotTelemetry_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::seagull_autopilot_msgs::AutopilotTelemetry_<ContainerAllocator> >
{
  static const char* value()
  {
    return "645d93bf5a3523d02fe4719dbe79be4b";
  }

  static const char* value(const ::seagull_autopilot_msgs::AutopilotTelemetry_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x645d93bf5a3523d0ULL;
  static const uint64_t static_value2 = 0x2fe4719dbe79be4bULL;
};

template<class ContainerAllocator>
struct DataType< ::seagull_autopilot_msgs::AutopilotTelemetry_<ContainerAllocator> >
{
  static const char* value()
  {
    return "seagull_autopilot_msgs/AutopilotTelemetry";
  }

  static const char* value(const ::seagull_autopilot_msgs::AutopilotTelemetry_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::seagull_autopilot_msgs::AutopilotTelemetry_<ContainerAllocator> >
{
  static const char* value()
  {
    return "seagull_commons_msgs/SeagullHeader header\n\
float32 latitude\n\
float32 longitude\n\
float32 altitude\n\
uint16 ias\n\
int16 vx\n\
int16 vy\n\
int16 vz\n\
int16 roll\n\
int16 pitch\n\
float32 yaw\n\
int16 barometricAltitude\n\
float32 windSouth\n\
float32 windWest\n\
uint16 leftRPM\n\
uint16 rightRPM\n\
uint16 staticPressure\n\
int16 accelX\n\
int16 accelY\n\
int16 accelZ\n\
uint16 compass\n\
uint16 agl\n\
uint64 timestamp #GMT posix timestamp converted from gps time \n\
float32 fuel\n\
================================================================================\n\
MSG: seagull_commons_msgs/SeagullHeader\n\
Header header\n\
uint16 vehicleId\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::seagull_autopilot_msgs::AutopilotTelemetry_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::seagull_autopilot_msgs::AutopilotTelemetry_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.latitude);
      stream.next(m.longitude);
      stream.next(m.altitude);
      stream.next(m.ias);
      stream.next(m.vx);
      stream.next(m.vy);
      stream.next(m.vz);
      stream.next(m.roll);
      stream.next(m.pitch);
      stream.next(m.yaw);
      stream.next(m.barometricAltitude);
      stream.next(m.windSouth);
      stream.next(m.windWest);
      stream.next(m.leftRPM);
      stream.next(m.rightRPM);
      stream.next(m.staticPressure);
      stream.next(m.accelX);
      stream.next(m.accelY);
      stream.next(m.accelZ);
      stream.next(m.compass);
      stream.next(m.agl);
      stream.next(m.timestamp);
      stream.next(m.fuel);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct AutopilotTelemetry_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::seagull_autopilot_msgs::AutopilotTelemetry_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::seagull_autopilot_msgs::AutopilotTelemetry_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::seagull_commons_msgs::SeagullHeader_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "latitude: ";
    Printer<float>::stream(s, indent + "  ", v.latitude);
    s << indent << "longitude: ";
    Printer<float>::stream(s, indent + "  ", v.longitude);
    s << indent << "altitude: ";
    Printer<float>::stream(s, indent + "  ", v.altitude);
    s << indent << "ias: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.ias);
    s << indent << "vx: ";
    Printer<int16_t>::stream(s, indent + "  ", v.vx);
    s << indent << "vy: ";
    Printer<int16_t>::stream(s, indent + "  ", v.vy);
    s << indent << "vz: ";
    Printer<int16_t>::stream(s, indent + "  ", v.vz);
    s << indent << "roll: ";
    Printer<int16_t>::stream(s, indent + "  ", v.roll);
    s << indent << "pitch: ";
    Printer<int16_t>::stream(s, indent + "  ", v.pitch);
    s << indent << "yaw: ";
    Printer<float>::stream(s, indent + "  ", v.yaw);
    s << indent << "barometricAltitude: ";
    Printer<int16_t>::stream(s, indent + "  ", v.barometricAltitude);
    s << indent << "windSouth: ";
    Printer<float>::stream(s, indent + "  ", v.windSouth);
    s << indent << "windWest: ";
    Printer<float>::stream(s, indent + "  ", v.windWest);
    s << indent << "leftRPM: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.leftRPM);
    s << indent << "rightRPM: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.rightRPM);
    s << indent << "staticPressure: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.staticPressure);
    s << indent << "accelX: ";
    Printer<int16_t>::stream(s, indent + "  ", v.accelX);
    s << indent << "accelY: ";
    Printer<int16_t>::stream(s, indent + "  ", v.accelY);
    s << indent << "accelZ: ";
    Printer<int16_t>::stream(s, indent + "  ", v.accelZ);
    s << indent << "compass: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.compass);
    s << indent << "agl: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.agl);
    s << indent << "timestamp: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.timestamp);
    s << indent << "fuel: ";
    Printer<float>::stream(s, indent + "  ", v.fuel);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SEAGULL_AUTOPILOT_MSGS_MESSAGE_AUTOPILOTTELEMETRY_H
