// Generated by gencpp from file seagull_autopilot_msgs/AutopilotUserAction.msg
// DO NOT EDIT!


#ifndef SEAGULL_AUTOPILOT_MSGS_MESSAGE_AUTOPILOTUSERACTION_H
#define SEAGULL_AUTOPILOT_MSGS_MESSAGE_AUTOPILOTUSERACTION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <seagull_commons_msgs/SeagullHeader.h>

namespace seagull_autopilot_msgs
{
template <class ContainerAllocator>
struct AutopilotUserAction_
{
  typedef AutopilotUserAction_<ContainerAllocator> Type;

  AutopilotUserAction_()
    : header()
    , action(0)
    , on(false)  {
    }
  AutopilotUserAction_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , action(0)
    , on(false)  {
    }



   typedef  ::seagull_commons_msgs::SeagullHeader_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _action_type;
  _action_type action;

   typedef uint8_t _on_type;
  _on_type on;


    enum { UA_ACTION0 = 0u };
     enum { UA_ACTION1 = 1u };
     enum { UA_ACTION2 = 2u };
     enum { UA_ACTION3 = 3u };
     enum { UA_ACTION4 = 4u };
     enum { UA_ACTION5 = 5u };
     enum { UA_ACTION6 = 6u };
     enum { UA_ACTION7 = 7u };
 

  typedef boost::shared_ptr< ::seagull_autopilot_msgs::AutopilotUserAction_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::seagull_autopilot_msgs::AutopilotUserAction_<ContainerAllocator> const> ConstPtr;

}; // struct AutopilotUserAction_

typedef ::seagull_autopilot_msgs::AutopilotUserAction_<std::allocator<void> > AutopilotUserAction;

typedef boost::shared_ptr< ::seagull_autopilot_msgs::AutopilotUserAction > AutopilotUserActionPtr;
typedef boost::shared_ptr< ::seagull_autopilot_msgs::AutopilotUserAction const> AutopilotUserActionConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::seagull_autopilot_msgs::AutopilotUserAction_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::seagull_autopilot_msgs::AutopilotUserAction_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace seagull_autopilot_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'seagull_autopilot_msgs': ['/home/administrator/sharpeye15/sharpeye15_ws/src/seagull_autopilot_msgs/msg'], 'seagull_commons_msgs': ['/home/administrator/sharpeye15/sharpeye15_ws/src/seagull_commons_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::seagull_autopilot_msgs::AutopilotUserAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::seagull_autopilot_msgs::AutopilotUserAction_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::seagull_autopilot_msgs::AutopilotUserAction_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::seagull_autopilot_msgs::AutopilotUserAction_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::seagull_autopilot_msgs::AutopilotUserAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::seagull_autopilot_msgs::AutopilotUserAction_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::seagull_autopilot_msgs::AutopilotUserAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3fa4894e20b298a9316812ce9cf223c7";
  }

  static const char* value(const ::seagull_autopilot_msgs::AutopilotUserAction_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3fa4894e20b298a9ULL;
  static const uint64_t static_value2 = 0x316812ce9cf223c7ULL;
};

template<class ContainerAllocator>
struct DataType< ::seagull_autopilot_msgs::AutopilotUserAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "seagull_autopilot_msgs/AutopilotUserAction";
  }

  static const char* value(const ::seagull_autopilot_msgs::AutopilotUserAction_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::seagull_autopilot_msgs::AutopilotUserAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "seagull_commons_msgs/SeagullHeader header\n\
uint8 	action\n\
bool 	on\n\
#ENUM Valid User actions\n\
	uint8 UA_ACTION0=0\n\
	uint8 UA_ACTION1=1\n\
	uint8 UA_ACTION2=2\n\
	uint8 UA_ACTION3=3\n\
	uint8 UA_ACTION4=4\n\
	uint8 UA_ACTION5=5\n\
	uint8 UA_ACTION6=6\n\
	uint8 UA_ACTION7=7\n\
\n\
================================================================================\n\
MSG: seagull_commons_msgs/SeagullHeader\n\
Header header\n\
uint16 vehicleId\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::seagull_autopilot_msgs::AutopilotUserAction_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::seagull_autopilot_msgs::AutopilotUserAction_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.action);
      stream.next(m.on);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct AutopilotUserAction_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::seagull_autopilot_msgs::AutopilotUserAction_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::seagull_autopilot_msgs::AutopilotUserAction_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::seagull_commons_msgs::SeagullHeader_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "action: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.action);
    s << indent << "on: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.on);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SEAGULL_AUTOPILOT_MSGS_MESSAGE_AUTOPILOTUSERACTION_H
