// Generated by gencpp from file seagull_autopilot_msgs/AutopilotMissionSettings.msg
// DO NOT EDIT!


#ifndef SEAGULL_AUTOPILOT_MSGS_MESSAGE_AUTOPILOTMISSIONSETTINGS_H
#define SEAGULL_AUTOPILOT_MSGS_MESSAGE_AUTOPILOTMISSIONSETTINGS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <seagull_commons_msgs/SeagullHeader.h>

namespace seagull_autopilot_msgs
{
template <class ContainerAllocator>
struct AutopilotMissionSettings_
{
  typedef AutopilotMissionSettings_<ContainerAllocator> Type;

  AutopilotMissionSettings_()
    : header()
    , altitude_min(0)
    , altitude_max(0)
    , fligth_timeout(0)  {
    }
  AutopilotMissionSettings_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , altitude_min(0)
    , altitude_max(0)
    , fligth_timeout(0)  {
    }



   typedef  ::seagull_commons_msgs::SeagullHeader_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int16_t _altitude_min_type;
  _altitude_min_type altitude_min;

   typedef int16_t _altitude_max_type;
  _altitude_max_type altitude_max;

   typedef uint32_t _fligth_timeout_type;
  _fligth_timeout_type fligth_timeout;




  typedef boost::shared_ptr< ::seagull_autopilot_msgs::AutopilotMissionSettings_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::seagull_autopilot_msgs::AutopilotMissionSettings_<ContainerAllocator> const> ConstPtr;

}; // struct AutopilotMissionSettings_

typedef ::seagull_autopilot_msgs::AutopilotMissionSettings_<std::allocator<void> > AutopilotMissionSettings;

typedef boost::shared_ptr< ::seagull_autopilot_msgs::AutopilotMissionSettings > AutopilotMissionSettingsPtr;
typedef boost::shared_ptr< ::seagull_autopilot_msgs::AutopilotMissionSettings const> AutopilotMissionSettingsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::seagull_autopilot_msgs::AutopilotMissionSettings_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::seagull_autopilot_msgs::AutopilotMissionSettings_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace seagull_autopilot_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'seagull_autopilot_msgs': ['/home/eloi/seagull_ws_dev/src/seagull_autopilot_msgs/msg'], 'seagull_commons_msgs': ['/home/eloi/seagull_ws_dev/src/seagull_commons_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::seagull_autopilot_msgs::AutopilotMissionSettings_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::seagull_autopilot_msgs::AutopilotMissionSettings_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::seagull_autopilot_msgs::AutopilotMissionSettings_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::seagull_autopilot_msgs::AutopilotMissionSettings_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::seagull_autopilot_msgs::AutopilotMissionSettings_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::seagull_autopilot_msgs::AutopilotMissionSettings_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::seagull_autopilot_msgs::AutopilotMissionSettings_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8b0ed07c0984f0d2fcee17bed5e0c1fd";
  }

  static const char* value(const ::seagull_autopilot_msgs::AutopilotMissionSettings_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8b0ed07c0984f0d2ULL;
  static const uint64_t static_value2 = 0xfcee17bed5e0c1fdULL;
};

template<class ContainerAllocator>
struct DataType< ::seagull_autopilot_msgs::AutopilotMissionSettings_<ContainerAllocator> >
{
  static const char* value()
  {
    return "seagull_autopilot_msgs/AutopilotMissionSettings";
  }

  static const char* value(const ::seagull_autopilot_msgs::AutopilotMissionSettings_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::seagull_autopilot_msgs::AutopilotMissionSettings_<ContainerAllocator> >
{
  static const char* value()
  {
    return "seagull_commons_msgs/SeagullHeader header\n\
int16 altitude_min\n\
int16 altitude_max\n\
uint32 fligth_timeout\n\
================================================================================\n\
MSG: seagull_commons_msgs/SeagullHeader\n\
Header header\n\
uint16 vehicleId\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::seagull_autopilot_msgs::AutopilotMissionSettings_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::seagull_autopilot_msgs::AutopilotMissionSettings_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.altitude_min);
      stream.next(m.altitude_max);
      stream.next(m.fligth_timeout);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct AutopilotMissionSettings_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::seagull_autopilot_msgs::AutopilotMissionSettings_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::seagull_autopilot_msgs::AutopilotMissionSettings_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::seagull_commons_msgs::SeagullHeader_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "altitude_min: ";
    Printer<int16_t>::stream(s, indent + "  ", v.altitude_min);
    s << indent << "altitude_max: ";
    Printer<int16_t>::stream(s, indent + "  ", v.altitude_max);
    s << indent << "fligth_timeout: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.fligth_timeout);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SEAGULL_AUTOPILOT_MSGS_MESSAGE_AUTOPILOTMISSIONSETTINGS_H
