Header header
uint8 node
      uint8 HB_AIS_DRIVER=0
      uint8 HB_GOBI_FG=1
      uint8 HB_JAI_FG=2
      uint8 HB_TASE_FG=3
      uint8 HB_DETECTION_MODULE=4
      uint8 HB_SEAGULL_MANAGER=5
      uint8 HB_TASE_DRIVER=6
      uint8 HB_TASE_COMMS=7      
      uint8 HB_COMMS_RELAY=8
      uint8 HB_AP_DRIVER=9
      uint8 HB_AP_COMMS=10
      uint8 HB_CONTROL_SUPERVISOR=11
      uint8 HB_TARGET_TRACKING=12
      uint8 HB_SENSE_AVOID=13
      uint8 HB_ADSB_DRIVER=14
      
      
