option(CI_JENKINS "enable jenkings build" OFF)

set(CI_JENKINGS_INCLUDE_HEADERS_DIR_LIST "" CACHE STRING "Include this directory to include_dirs")
set(CI_JENKINGS_LINK_DIR_LIST "" CACHE STRING "Include this directory to add_library")
#------------------------------------------------------
macro(jenkins_includes_dir )
if (CI_JENKINS)
    message(STATUS "*** Called Jenkins Include Directory")
    if(CI_JENKINGS_INCLUDE_HEADERS_DIR_LIST)   
        string( REPLACE "|" ";" JenkinsHeadersIncludeDirList ${CI_JENKINGS_INCLUDE_HEADERS_DIR_LIST} )
        foreach( JenkinsHeadersIncludeDir ${JenkinsHeadersIncludeDirList} )
            include_directories(${JenkinsHeadersIncludeDir})
            message(STATUS "*** Jenkins Include Directory= ${JenkinsHeadersIncludeDir}")
        endforeach( JenkinsHeadersIncludeDir)
    endif(CI_JENKINGS_INCLUDE_HEADERS_DIR_LIST)
endif(CI_JENKINS)
endmacro(jenkins_includes_dir )
#------------------------------------------------------
macro(jenkins_link_libraries )
if (CI_JENKINS)
    message(STATUS "*** Called Jenkins Link Directory")
    if (CI_JENKINGS_LINK_DIR_LIST)
        string( REPLACE "|" ";" JenkinsLinkDirList ${CI_JENKINGS_LINK_DIR_LIST} )
        foreach( JenkinsLinkDir ${JenkinsLinkDirList} )
            link_directories(${JenkinsLinkDir})
            message(STATUS "***Jenkins Link Directory= ${JenkinsLinkDir}")
        endforeach( JenkinsLinkDir)
    endif (CI_JENKINGS_LINK_DIR_LIST)
endif(CI_JENKINS)
endmacro(jenkins_link_libraries)

