(cl:in-package seagull_autopilot_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          LATITUDE-VAL
          LATITUDE
          LONGITUDE-VAL
          LONGITUDE
          DEPLOYPARACHUTE-VAL
          DEPLOYPARACHUTE
          DEPLOYDROP-VAL
          DEPLOYDROP
          ORBITDIRECTION-VAL
          ORBITDIRECTION
          CAMERATARGET-VAL
          CAMERATARGET
          LANDINGPOINT-VAL
          LANDINGPOINT
          SLOPECONTROL-VAL
          SLOPECONTROL
          LIGHTSON-VAL
          LIGHTSON
          PRETURN-VAL
          PRETURN
          ORBITRADIUS-VAL
          ORBITRADIUS
          ALTITUDE-VAL
          ALTITUDE
          WINDFIND-VAL
          WINDFIND
          ORBITTIME-VAL
          ORBITTIME
          INDEX-VAL
          INDEX
          NEXT-VAL
          NEXT
          USER-VAL
          USER
          ORBITABOVE-VAL
          ORBITABOVE
          ORBITBELOW-VAL
          ORBITBELOW
          HOVERPOINT-VAL
          HOVERPOINT
          ALTITUDETOGROUND-VAL
          ALTITUDETOGROUND
          ORBITMULTIPLIER50-VAL
          ORBITMULTIPLIER50
          ALTLSB-VAL
          ALTLSB
))