(cl:in-package seagull_autopilot_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          LATITUDE-VAL
          LATITUDE
          LONGITUDE-VAL
          LONGITUDE
          ALTITUDE-VAL
          ALTITUDE
          IAS-VAL
          IAS
          VX-VAL
          VX
          VY-VAL
          VY
          VZ-VAL
          VZ
          ROLL-VAL
          ROLL
          PITCH-VAL
          PITCH
          YAW-VAL
          YAW
          BAROMETRICALTITUDE-VAL
          BAROMETRICALTITUDE
          WINDSOUTH-VAL
          WINDSOUTH
          WINDWEST-VAL
          WINDWEST
          LEFTRPM-VAL
          LEFTRPM
          RIGHTRPM-VAL
          RIGHTRPM
          STATICPRESSURE-VAL
          STATICPRESSURE
          ACCELX-VAL
          ACCELX
          ACCELY-VAL
          ACCELY
          ACCELZ-VAL
          ACCELZ
          COMPASS-VAL
          COMPASS
          AGL-VAL
          AGL
          TIMESTAMP-VAL
          TIMESTAMP
          FUEL-VAL
          FUEL
))